Repository NetchaProject/netcha, pull requests merged in 2023-08, with the labels that each got.

#9 [UI] 업데이트 내용
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/netcha/MainPage.kt
  app/src/main/java/com/example/netcha/SignInActivity.kt
  app/src/main/res/layout/activity_main_page.xml
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values-night/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#14 [UI]mainpage
  app/src/main/java/com/example/netcha/MainPage.kt
  app/src/main/java/com/example/netcha/SignInActivity.kt
  app/src/main/java/com/example/netcha/SignUpActivity.kt
  app/src/main/res/layout/activity_main_page.xml
Labels: feature

#19 [UI] update third commit
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/netcha/MainPage.kt
  app/src/main/java/com/example/netcha/SignInActivity.kt
  app/src/main/java/com/example/netcha/Splash.kt
  app/src/main/java/com/example/netcha/UserDataFind.kt
  app/src/main/res/drawable-xxxhdpi/logout_button.png
  app/src/main/res/drawable/logout_button.png
  app/src/main/res/drawable/main_page_profile_shape.xml
  app/src/main/res/layout/activity_main_page.xml
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/activity_user_data_find.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values-night/strings.xml
  app/src/main/res/values/mainpage_style_toolbar.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: feature

#20 password feature update
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/netcha/MainPage.kt
  app/src/main/java/com/example/netcha/SignUpActivity.kt
  app/src/main/res/layout/activity_movie_detail_page1.xml
  app/src/main/res/layout/activity_movie_detail_page2.xml
  app/src/main/res/layout/activity_movie_detail_page3.xml
  app/src/main/res/layout/activity_movie_detail_page4.xml
  app/src/main/res/layout/activity_sigin_up.xml
  app/src/main/res/values-en/strings.xml
Labels: feature

#21 [Fix]detailpage- 기능 추가
  app/src/main/java/com/example/netcha/MovieDetailPage1.kt
  app/src/main/java/com/example/netcha/MovieDetailPage2.kt
  app/src/main/java/com/example/netcha/MovieDetailPage3.kt
Labels: feature

#23 [UI]update userdatafind
  app/src/main/java/com/example/netcha/SignUpActivity.kt
  app/src/main/res/drawable/happydog3.png
  app/src/main/res/drawable/happydog4.png
  app/src/main/res/drawable/happydog5.png
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/layout/activity_user_data_find.xml
  app/src/main/res/values-en/strings.xml
Labels: UI

#24 textwatcher update
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/netcha/SignUpActivity.kt
  app/src/main/java/com/example/netcha/UserData.kt
  app/src/main/res/drawable/logo_red.xml
  app/src/main/res/layout/activity_movie_detail_page4.xml
  app/src/main/res/layout/activity_sigin_up.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values-night/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#26 add string kr/night/en/
  app/src/main/res/layout/activity_user_data_find.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values-night/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#27 userdata update and textwatcher modify
  app/src/main/java/com/example/netcha/SignUpActivity.kt
  app/src/main/java/com/example/netcha/UserData.kt
  app/src/main/res/values-night/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#29 [feat] update SignInActivity
  app/src/main/java/com/example/netcha/SignInActivity.kt
  app/src/main/java/com/example/netcha/UserData.kt
  app/src/main/res/layout/activity_sign_in.xml
Labels: feature

#30 feature / userdatafind page
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/netcha/UserData.kt
  app/src/main/java/com/example/netcha/UserDataFind.kt
  app/src/main/res/drawable/logout_button.png
  app/src/main/res/layout/activity_main_page.xml
  app/src/main/res/layout/activity_movie_detail_page1.xml
  app/src/main/res/layout/activity_movie_detail_page2.xml
  app/src/main/res/layout/activity_movie_detail_page3.xml
  app/src/main/res/layout/activity_movie_detail_page4.xml
  app/src/main/res/layout/activity_movie_detail_page5.xml
  app/src/main/res/layout/activity_movie_detail_page6.xml
  app/src/main/res/layout/activity_user_data_find.xml
  gradle.properties
Labels: feature

#32 [기능] 마지막 커밋 회원 가입 UI, 기능 수정
  app/src/main/java/com/example/netcha/MainPage.kt
  app/src/main/java/com/example/netcha/SignInActivity.kt
  app/src/main/java/com/example/netcha/SignUpActivity.kt
  app/src/main/res/layout/activity_main_page.xml
  app/src/main/res/layout/activity_sigin_up.xml
  app/src/main/res/values/strings.xml
Labels: feature

#33 userdatafind 기능 구현 완료 / 폰트 통일
  app/src/main/java/com/example/netcha/UserDataFind.kt
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/layout/activity_user_data_find.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values-night/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature, UI

#34 app icon update
  app/src/main/AndroidManifest.xml
  app/src/main/app_icon-playstore.png
  app/src/main/java/com/example/netcha/SignUpActivity.kt
  app/src/main/java/com/example/netcha/UserData.kt
  app/src/main/java/com/example/netcha/UserDataFind.kt
  app/src/main/res/drawable/netcha_appicon.xml
  app/src/main/res/mipmap-anydpi-v26/app_icon.xml
  app/src/main/res/mipmap-anydpi-v26/app_icon_round.xml
  app/src/main/res/mipmap-hdpi/app_icon.png
  app/src/main/res/mipmap-hdpi/app_icon_foreground.png
  app/src/main/res/mipmap-hdpi/app_icon_round.png
  app/src/main/res/mipmap-mdpi/app_icon.png
  app/src/main/res/mipmap-mdpi/app_icon_foreground.png
  app/src/main/res/mipmap-mdpi/app_icon_round.png
  app/src/main/res/mipmap-xhdpi/app_icon.png
  app/src/main/res/mipmap-xhdpi/app_icon_foreground.png
  app/src/main/res/mipmap-xhdpi/app_icon_round.png
  app/src/main/res/mipmap-xxhdpi/app_icon.png
  app/src/main/res/mipmap-xxhdpi/app_icon_foreground.png
  app/src/main/res/mipmap-xxhdpi/app_icon_round.png
  app/src/main/res/mipmap-xxxhdpi/app_icon.png
  app/src/main/res/mipmap-xxxhdpi/app_icon_foreground.png
  app/src/main/res/mipmap-xxxhdpi/app_icon_round.png
  app/src/main/res/values/app_icon_background.xml
Labels: UI

#36 [DESIGN] : 🎨123456detailpage
  app/src/main/java/com/example/netcha/MainPage.kt
  app/src/main/java/com/example/netcha/MovieDetailPage1.kt
  app/src/main/java/com/example/netcha/MovieDetailPage2.kt
  app/src/main/java/com/example/netcha/MovieDetailPage3.kt
  app/src/main/java/com/example/netcha/SignUpActivity.kt
  app/src/main/res/layout/activity_movie_detail_page1.xml
  app/src/main/res/layout/activity_movie_detail_page3.xml
Labels: bug

#37 final feature
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/netcha/SignInActivity.kt
  app/src/main/res/layout/activity_main_page.xml
  app/src/main/res/layout/activity_sigin_up.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values-night/strings.xml
  app/src/main/res/values/mainpage_style_toolbar.xml
  app/src/main/res/values/strings.xml
Labels: feature, UI

#38 [UI] 진짜 마지막 커밋 일부 UI 수정
  app/src/main/java/com/example/netcha/MainPage.kt
  app/src/main/res/layout/activity_main_page.xml
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values-night/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature, UI
